### ISSUE TITLE
Calibration task

### ISSUE THREAD

**Issue by glopesdev** [spewil/kyberphysics#1]
Calibration sequence for each subject

1. Display grid matching electrode layout (4x2, 4x4, 4x8, 8x8)
2. From python receive electrode index to highlight
3. Run calibration trial:
  a. Collect raw data (S32) (samples,channels) for a fixed number of samples for each trial
  b. Real-time feedback of activity (rectified, filtered and projected on color/size/other scale for each electrode dot in the grid)
4. Return control to python and wait for next electrode index or end of calibration
5. Store calibration data as one single file structured as a cube (samples,channels,trials)
6. Store metadata for calibration:
  a. Highlighted channel index for each trial

**Comment by spewil** [comment]
Testing with physical hardware:
- Recording from device (plain test recording triggered from Python) 
- Direct mapping from EMG to dot colors
- Test calibration data from Bonsai matches expected inputs
